apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: jira-service
  replicas: 1
  template:
    metadata:
      labels:
        run: jira-service
    spec:
      containers:
      - name: jira-service
        image: mvilliger/jira-service:0.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: JIRA_HOSTNAME
          valueFrom:
            secretKeyRef:
                name: jira-service
                key: jira-hostname
        - name: JIRA_USERNAME
          valueFrom:
            secretKeyRef:
                name: jira-service
                key: jira-username
        - name: JIRA_TOKEN
          valueFrom:
            secretKeyRef:
                name: jira-service
                key: jira-token

---
apiVersion: v1
kind: Service
metadata:
  name: jira-service
  namespace: keptn
  labels:
    run: jira-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: jira-service
