---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: jira-service
  replicas: 1
  template:
    metadata:
      labels:
        run: jira-service
    spec:
      containers:
      - name: jira-service
        image: keptnsandbox/jira-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: JIRA_BASE_URL
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-base-url
        - name: JIRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-username
        - name: JIRA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-api-token
        - name: JIRA_PROJECT_KEY
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-project-key
        - name: JIRA_ISSUE_TYPE
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-issue-type
        - name: JIRA_TICKET_FOR_PROBLEMS
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-create-ticket-for-problems
        - name: JIRA_TICKET_FOR_EVALUATIONS
          valueFrom:
            secretKeyRef:
              name: jira-details
              key: jira-create-ticket-for-evaluations
        - name: DT_TENANT
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: DT_TENANT
              optional: true
        - name: KEPTN_DOMAIN
          value: 'http://keptn.54.144.62.54.nip.io/'
        - name: KEPTN_BRIDGE_URL
          value: 'http://keptn.54.144.62.54.nip.io/bridge'
---
apiVersion: v1
kind: Service
metadata:
  name: jira-service
  namespace: keptn
  labels:
    run: jira-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: jira-service
